### ISSUE TITLE
Tooltip getting out of bounds

### ISSUE THREAD

**Issue by HagegeR** [jenkins-infra/stats.jenkins.io#48] opened 2024-06-21 11:45 UTC
### Reproduction steps

![image](https://github.com/jenkins-infra/stats.jenkins.io/assets/20857346/ed26ef50-b981-466e-971a-1bd345ff6303)
https://deploy-preview-45--stats-jenkins-io.netlify.app/plugin-trends

I'm not sure if the correct answer for this would be to have:

1. The legend be offset to permit full view of it's content
2. The legend get out of the bounds of the pane it's linked to
3. The legend to show in a side of the screen that permits it full view

All of the above could have edge cases, a combination of those might be needed

### Expected Results

full view of the legend text

### Actual Results

partially occluded view

**Comment by Vandit1604** [comment] 2024-06-28 12:48
@krisstern @lemeurherve 

We can close this, since we ended up removing the legend completely.
See here #49

**Comment by Vandit1604** [comment] 2024-06-28 15:13
Hey @HagegeR 
I checked https://deploy-preview-45--stats-jenkins-io.netlify.app/plugin-trends, and I'm unable to reproduce normally, but if I zoom In to the page, I can reproduce it. 

Can you give more details about the browser you're using? Or custom settings related to Page Zoom.
Thanks for reporting!

**Comment by lemeurherve** [comment] 2024-06-28 20:34
@Vandit1604 HagegeR won't be able to answer here until end of GSoC (cf https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2182602543)

**Comment by HagegeR** [comment] 2024-07-25 16:13
hey, I see I'm able to answer now, is the question still relevant?

**Comment by HagegeR** [comment] 2024-07-29 15:25
interestingly I just found a bug while trying to go to this link:
It's possible to navigate from https://new.stats.jenkins.io/ to https://new.stats.jenkins.io/plugin-trends
but not to access https://new.stats.jenkins.io/plugin-trends directly:
![image](https://github.com/user-attachments/assets/34873d1a-32e4-420b-83db-f1b5e08462e2)
now most of the issues have been fixed, but this issue still exist in some cases:
![image](https://github.com/user-attachments/assets/d0dd75c6-ec01-479b-afbe-28179d231657)

**Comment by lemeurherve** [comment] 2024-07-29 15:31
See #118

Le lun. 29 juil. 2024, 17:26, Hagege Ruben ***@***.***> a
écrit :

**Comment by KitsuneKode** [comment] 2024-11-14 09:56
Is this issue taken up by anyone?
I see no PRs raised, so, I will work on it.

@krisstern

**Comment by krisstern** [comment] 2024-11-14 10:03
Hi @KitsuneKode, I think you should check to see if the issue is still there. This is because from the above conversation it may have already been resolved.

**Comment by KitsuneKode** [comment] 2024-11-14 10:11
@krisstern I think this issue no longer exists.
I could not replicate it

**Comment by krisstern** [comment] 2024-11-14 10:45
@KitsuneKode Thanks for checking and confirming for us! Let me close it then.

**Closed by krisstern** 2024-11-14 10:45 UTC
Labels: bug
